"""
doc_generator.py — ReportLab PDF generator for Vaakya contracts.

Public API:
    generate_contract_pdf(state, document_title="") -> bytes

Two modes:
  • state["draft"] is set  → formal contract PDF  (new_doc sub-graph)
  • state["draft"] is empty → redline report PDF   (redline sub-graph)
"""

import io
import re
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from graph.state import VaakyaState

# ── Colours ────────────────────────────────────────────────────────────────────

_C_BRAND  = HexColor("#1a1a2e")   # dark navy header
_C_ACCENT = HexColor("#e94560")   # red accent rule
_C_HIGH   = HexColor("#c0392b")
_C_MEDIUM = HexColor("#e67e22")
_C_LOW    = HexColor("#7f8c8d")
_C_LIGHT  = HexColor("#f8f9fa")   # table row background
_C_WHITE  = colors.white

_MARGIN = 2.0 * cm

# ── Styles ─────────────────────────────────────────────────────────────────────

_base = getSampleStyleSheet()

_S_HEADER_BRAND = ParagraphStyle(
    "HeaderBrand",
    fontName="Helvetica-Bold",
    fontSize=14,
    textColor=_C_WHITE,
    alignment=TA_LEFT,
)
_S_HEADER_DATE = ParagraphStyle(
    "HeaderDate",
    fontName="Helvetica",
    fontSize=9,
    textColor=_C_WHITE,
    alignment=TA_RIGHT,
)
_S_TITLE = ParagraphStyle(
    "DocTitle",
    fontName="Helvetica-Bold",
    fontSize=16,
    textColor=_C_BRAND,
    alignment=TA_CENTER,
    spaceAfter=6,
)
_S_SUBTITLE = ParagraphStyle(
    "DocSubtitle",
    fontName="Helvetica",
    fontSize=11,
    textColor=_C_LOW,
    alignment=TA_CENTER,
    spaceAfter=12,
)
_S_HEADING1 = ParagraphStyle(
    "ClauseHeading",
    fontName="Helvetica-Bold",
    fontSize=11,
    textColor=_C_BRAND,
    spaceBefore=12,
    spaceAfter=4,
)
_S_BODY = ParagraphStyle(
    "Body",
    fontName="Helvetica",
    fontSize=10,
    leading=14,
    spaceAfter=6,
    alignment=TA_LEFT,
)
_S_LABEL = ParagraphStyle(
    "Label",
    fontName="Helvetica-Bold",
    fontSize=9,
    textColor=_C_LOW,
    spaceAfter=2,
)
_S_SMALL = ParagraphStyle(
    "Small",
    fontName="Helvetica",
    fontSize=8,
    textColor=_C_LOW,
)
_S_RISK_TEXT = ParagraphStyle(
    "RiskText",
    fontName="Helvetica",
    fontSize=9,
    leading=13,
    spaceAfter=4,
)
_S_CLAUSE_REF = ParagraphStyle(
    "ClauseRef",
    fontName="Helvetica-Bold",
    fontSize=10,
    textColor=_C_BRAND,
    spaceBefore=10,
    spaceAfter=3,
)
_S_CURRENT = ParagraphStyle(
    "Current",
    fontName="Helvetica-Oblique",
    fontSize=9,
    textColor=HexColor("#555555"),
    leading=13,
    leftIndent=12,
    spaceAfter=4,
)
_S_PROPOSED = ParagraphStyle(
    "Proposed",
    fontName="Helvetica",
    fontSize=9,
    textColor=HexColor("#1a6b1a"),
    leading=13,
    leftIndent=12,
    spaceAfter=4,
)
_S_REASON = ParagraphStyle(
    "Reason",
    fontName="Helvetica-Oblique",
    fontSize=8,
    textColor=_C_LOW,
    leftIndent=12,
    spaceAfter=8,
)

# ── Heading line detection ─────────────────────────────────────────────────────

_HEADING_RE = re.compile(
    r"^(\d+\.\d*\s|[A-Z][A-Z\s]{5,}:?$|SCHEDULE|APPENDIX|ANNEXURE|EXHIBIT|RECITALS?|WHEREAS)"
)


def _is_heading(line: str) -> bool:
    stripped = line.strip()
    return bool(stripped and _HEADING_RE.match(stripped)) and len(stripped) < 120


# ── Page footer callback ───────────────────────────────────────────────────────

def _footer(canvas, doc):
    canvas.saveState()
    w, _ = A4
    footer_text = (
        f"Page {doc.page}  |  Jurisdiction: India  |  "
        "Indian Contract Act, 1872  |  Generated by Vaakya"
    )
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_C_LOW)
    canvas.drawCentredString(w / 2, 1.0 * cm, footer_text)
    canvas.restoreState()


# ── Brand header block ─────────────────────────────────────────────────────────

def _header_table(title_line: str, subtitle_line: str, date_str: str) -> list:
    """Returns a list of flowables: coloured header bar + title + subtitle."""
    header_data = [
        [Paragraph("VAAKYA", _S_HEADER_BRAND), Paragraph(date_str, _S_HEADER_DATE)],
    ]
    header_tbl = Table(header_data, colWidths=["70%", "30%"])
    header_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), _C_BRAND),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (0, -1), 14),
        ("RIGHTPADDING",  (-1, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    flowables = [
        header_tbl,
        Spacer(1, 14),
        Paragraph(title_line, _S_TITLE),
    ]
    if subtitle_line:
        flowables.append(Paragraph(subtitle_line, _S_SUBTITLE))
    flowables += [
        HRFlowable(width="100%", thickness=2, color=_C_ACCENT, spaceAfter=10),
    ]
    return flowables


# ── Parties block ──────────────────────────────────────────────────────────────

def _parties_block(parties: list[dict]) -> list:
    if not parties:
        return []
    rows = [["Party", "Role"]]
    for p in parties:
        rows.append([
            Paragraph(p.get("name", "—"), _S_BODY),
            Paragraph(p.get("role", "—"), _S_BODY),
        ])
    tbl = Table(rows, colWidths=["60%", "40%"])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0),  _C_BRAND),
        ("TEXTCOLOR",    (0, 0), (-1, 0),  _C_WHITE),
        ("FONTNAME",     (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0),  9),
        ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",     (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_C_LIGHT, _C_WHITE]),
        ("GRID",         (0, 0), (-1, -1), 0.5, HexColor("#dddddd")),
        ("TOPPADDING",   (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    return [tbl, Spacer(1, 8)]


# ── Obligations appendix ───────────────────────────────────────────────────────

def _obligations_section(obligations: list[dict]) -> list:
    if not obligations:
        return []
    flowables: list = [
        PageBreak(),
        Paragraph("APPENDIX A — OBLIGATIONS SCHEDULE", _S_HEADING1),
        HRFlowable(width="100%", thickness=1, color=_C_ACCENT, spaceAfter=8),
    ]
    # Build table: detect available keys
    sample = obligations[0] if obligations else {}
    keys = [k for k in ("party", "action", "deadline", "consequence") if k in sample]
    if not keys:
        keys = list(sample.keys())[:4]
    headers = [k.replace("_", " ").title() for k in keys]
    rows = [headers] + [[Paragraph(str(ob.get(k, "—")), _S_RISK_TEXT) for k in keys] for ob in obligations]
    col_w = (17.0 * cm) / len(keys)
    tbl = Table(rows, colWidths=[col_w] * len(keys))
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  _C_BRAND),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  _C_WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0),  9),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [_C_LIGHT, _C_WHITE]),
        ("GRID",          (0, 0), (-1, -1), 0.5, HexColor("#dddddd")),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    flowables.append(tbl)
    return flowables


# ── Risk summary appendix ──────────────────────────────────────────────────────

def _risk_section(risk_flags: list[dict]) -> list:
    if not risk_flags:
        return []
    flowables: list = [
        Spacer(1, 16),
        Paragraph("APPENDIX B — RISK SUMMARY", _S_HEADING1),
        HRFlowable(width="100%", thickness=1, color=_C_ACCENT, spaceAfter=8),
    ]
    sample = risk_flags[0] if risk_flags else {}
    sev_key   = next((k for k in ("severity", "risk_level", "level") if k in sample), None)
    desc_key  = next((k for k in ("description", "issue", "detail", "summary") if k in sample), None)
    clause_key = next((k for k in ("clause_reference", "clause", "section") if k in sample), None)

    for flag in risk_flags:
        sev   = str(flag.get(sev_key, "INFO")).upper() if sev_key else "INFO"
        desc  = str(flag.get(desc_key, str(flag))) if desc_key else str(flag)
        clause = str(flag.get(clause_key, "")) if clause_key else ""
        badge_color = {"HIGH": _C_HIGH, "MEDIUM": _C_MEDIUM, "LOW": _C_LOW}.get(sev, _C_LOW)

        badge_data = [[Paragraph(f"  {sev}  ", ParagraphStyle(
            "Badge", fontName="Helvetica-Bold", fontSize=8, textColor=_C_WHITE,
        ))]]
        badge = Table(badge_data, colWidths=[1.8 * cm])
        badge.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), badge_color),
            ("TOPPADDING",    (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        row_data = [[badge, Paragraph(
            f"{'<b>' + clause + '</b> — ' if clause else ''}{desc}",
            _S_RISK_TEXT,
        )]]
        row_tbl = Table(row_data, colWidths=[2.0 * cm, 15.0 * cm])
        row_tbl.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (0, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        flowables.append(row_tbl)
    return flowables


# ── Signature block ────────────────────────────────────────────────────────────

def _signature_block(parties: list[dict]) -> list:
    party_a = parties[0].get("name", "Party A") if len(parties) > 0 else "Party A"
    party_b = parties[1].get("name", "Party B") if len(parties) > 1 else "Party B"
    sig_data = [
        [Paragraph("AUTHORISED SIGNATORY", _S_LABEL), Paragraph("AUTHORISED SIGNATORY", _S_LABEL)],
        [Paragraph(f"For: {party_a}", _S_BODY),       Paragraph(f"For: {party_b}", _S_BODY)],
        [Paragraph("Name:  _____________________", _S_SMALL), Paragraph("Name:  _____________________", _S_SMALL)],
        [Paragraph("Title: _____________________", _S_SMALL), Paragraph("Title: _____________________", _S_SMALL)],
        [Paragraph("Date:  _____________________", _S_SMALL), Paragraph("Date:  _____________________", _S_SMALL)],
        [Paragraph("Seal:  _____________________", _S_SMALL), Paragraph("Seal:  _____________________", _S_SMALL)],
    ]
    tbl = Table(sig_data, colWidths=["50%", "50%"])
    tbl.setStyle(TableStyle([
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("LINEABOVE",     (0, 0), (-1, 0),  1, _C_BRAND),
    ]))
    return [
        Spacer(1, 24),
        Paragraph("IN WITNESS WHEREOF", _S_HEADING1),
        HRFlowable(width="100%", thickness=1, color=HexColor("#dddddd"), spaceAfter=8),
        tbl,
    ]


# ── Contract PDF (new_doc flow) ────────────────────────────────────────────────

def _build_contract_pdf(state: VaakyaState, document_title: str) -> list:
    parties     = state.get("parties", [])
    jurisdiction = state.get("jurisdiction", "India")
    draft       = state.get("draft", "")
    obligations = state.get("obligations", [])
    risk_flags  = state.get("risk_flags", [])

    # Derive fallback title
    if not document_title:
        names = [p.get("name", "") for p in parties[:2]]
        doc_type = state.get("document_type", "Agreement")
        document_title = f"{doc_type} — {' & '.join(n for n in names if n)}" if names else doc_type

    date_str = datetime.now(timezone.utc).strftime("%d %b %Y")

    flowables: list = []
    flowables += _header_table(document_title, state.get("document_type", ""), date_str)

    # Jurisdiction meta line
    flowables.append(Paragraph(
        f"Governing Law: Indian Contract Act, 1872  |  Jurisdiction: {jurisdiction}",
        _S_SMALL,
    ))
    flowables.append(Spacer(1, 10))
    flowables += _parties_block(parties)
    flowables.append(HRFlowable(width="100%", thickness=1, color=HexColor("#dddddd"), spaceAfter=12))

    # Contract body
    for line in draft.splitlines():
        stripped = line.strip()
        if not stripped:
            flowables.append(Spacer(1, 4))
            continue
        # Escape XML special chars for ReportLab
        safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if _is_heading(stripped):
            flowables.append(Paragraph(safe, _S_HEADING1))
        else:
            flowables.append(Paragraph(safe, _S_BODY))

    flowables += _obligations_section(obligations)
    flowables += _risk_section(risk_flags)
    flowables += _signature_block(parties)
    return flowables


# ── Redline Report PDF (redline flow) ─────────────────────────────────────────

def _risk_badge_inline(risk_level: str) -> str:
    """Returns a coloured text tag for inline use in a Paragraph (ReportLab XML)."""
    colour_map = {"HIGH": "#c0392b", "MEDIUM": "#e67e22", "LOW": "#7f8c8d"}
    colour = colour_map.get(risk_level.upper(), "#7f8c8d")
    return f'<font color="{colour}"><b>[{risk_level.upper()}]</b></font>'


def _build_redline_pdf(state: VaakyaState, document_title: str) -> list:
    parties    = state.get("parties", [])
    redlines   = state.get("negotiation_redlines", [])
    doc_type   = state.get("document_type", "Agreement")
    date_str   = datetime.now(timezone.utc).strftime("%d %b %Y")

    title = document_title or f"Redline Report — {doc_type}"

    flowables: list = []
    flowables += _header_table(title, "VAAKYA REDLINE REPORT", date_str)
    flowables += _parties_block(parties)

    if not redlines:
        flowables.append(Paragraph("No redlines were flagged for this document.", _S_BODY))
        return flowables

    for rd in redlines:
        clause_ref     = str(rd.get("clause_reference", "Unknown Clause"))
        current_text   = str(rd.get("current_text", ""))
        recommendation = str(rd.get("recommendation", "counter")).lower()
        counter        = str(rd.get("counter_proposal", ""))
        risk_level     = str(rd.get("risk_level", "LOW")).upper()
        reason         = str(rd.get("reason", ""))

        # Safe XML encoding
        def _s(t: str) -> str:
            return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

        flowables.append(Paragraph(
            f"{_s(clause_ref)}  {_risk_badge_inline(risk_level)}",
            _S_CLAUSE_REF,
        ))

        if current_text:
            flowables.append(Paragraph("<b>CURRENT:</b>", _S_LABEL))
            flowables.append(Paragraph(_s(current_text), _S_CURRENT))

        flowables.append(Paragraph("<b>PROPOSED:</b>", _S_LABEL))
        if recommendation == "accept":
            flowables.append(Paragraph("ACCEPT — no change required.", _S_PROPOSED))
        elif recommendation == "reject":
            flowables.append(Paragraph("REJECT — delete this clause.", _S_PROPOSED))
        else:
            flowables.append(Paragraph(_s(counter) if counter else "See reason below.", _S_PROPOSED))

        if reason:
            flowables.append(Paragraph(f"<i>{_s(reason)}</i>", _S_REASON))

        flowables.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#dddddd"), spaceAfter=6))

    return flowables


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_contract_pdf(state: VaakyaState, document_title: str = "") -> bytes:
    """
    Generate a contract PDF from VaakyaState.

    Returns raw PDF bytes. Caller is responsible for uploading to storage.
    Chooses contract layout when state["draft"] is set; redline layout otherwise.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=_MARGIN,
        rightMargin=_MARGIN,
        topMargin=_MARGIN,
        bottomMargin=1.8 * cm,
        title=document_title or state.get("document_type", "Vaakya Contract"),
        author="Vaakya — Autonomous Legal Document Factory",
    )

    if state.get("draft"):
        flowables = _build_contract_pdf(state, document_title)
    else:
        flowables = _build_redline_pdf(state, document_title)

    doc.build(flowables, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
